baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Adopt a pet'
theme = "ananke"

[params]
  homepage_image = "/images/homepage-image.jpg"
  description = "A simple and elegant Hugo blog"
