name: Deploy Hugo site

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.121.1'
        extended: true

    - name: Setup Node (if needed for PostCSS or similar)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      run: |
        cd public
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy site [ci skip]"
        git branch -M gh-pages
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ThomasCREPINGE/adopt-a-pet.git
        git push -f origin gh-pages


